Feature/exercicio 1
brennerpaiva/orion-bootcamp-exercises pull request #1
Opened 2023-10-10 17:15 UTC by brennerpaiva

1 - Criar uma função que retorne a quantidade de vogais da palavra passada.
a) Dar um exemplo de uso com uma palavra recebida via parâmetro da função.
b) Dar um exemplo de uso com uma palavra recebida via input no formulário.

2023-10-11 02:35 UTC, arthurpaesrizon requested changes

2023-10-11 02:35 UTC, arthurpaesrizon commented on src/exercicio-01/main.ts
> +  const vogais = "aeiouAEIOU";
Podes só tipar essas duas variáveis aqui

2023-10-11 02:35 UTC, arthurpaesrizon commented on src/exercicio-01/main.ts
> +  const vogais = "aeiouAEIOU";
Podes verificar para vogais com acento também e não precisas acrescentar as vogais maiúsculas, podes forçar tudo para minúsculo com toLowerCase

2023-10-11 02:36 UTC, arthurpaesrizon commented
Acabou commitando o node_modules também.

2023-10-11 02:41 UTC, arthurpaesrizon requested changes

2023-10-11 02:41 UTC, arthurpaesrizon commented on package.json
> +    "typescript": "^5.2.2"
É bom fixar as versões dos pacotes

2023-10-12 00:42 UTC, brennerpaiva commented on package.json
> +    "typescript": "^5.2.2"
Show! Feita as alterações

2023-10-12 02:40 UTC, arthurpaesrizon approved these changes

2023-10-12 02:40 UTC, merged